### ISSUE TITLE
Logbox warning

### ISSUE THREAD

**Issue by pronouncedJerry** [WataruMaeda/react-native-boilerplate#13]
Thank you for putting this together. I am relatively new to react native so this boilerplate is immensely useful. Just a heads up that upon starting the app, the following warning is displayed:

```
Compiled with warnings.
/Users/me/dev/react/newapp/src/utils/ignore.js
Attempted import error: 'LogBox' is not exported from 'react-native-web/dist/index'.
```

**Comment by wataru-maeda** [comment]
Hi @pronouncedJerry , thanks for letting me know. I'm glad to hear you said the boilerplate is useful. Sure, let me fix the logbox import error when I have time, thanks!

**Comment by prawee** [comment]
same issue

**Comment by wataru-maeda** [comment]
The LogBox issue comes when you run in web browser. Just in case, I added optional chaining to avoid crashes on web #14 .

I would like to keep the Logbox ignore lines for mobile. So please feel free to remove [import ignore](https://github.com/WataruMaeda/react-native-boilerplate/blob/master/src/App.js#L5) for web in your convenience, thanks
