### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by KartikDevelopment** [WataruMaeda/react-native-boilerplate#47]
Can you specify exact node version

**Comment by wataru-maeda** [comment]
Sorry to miss your question for a while. It should work with node version v16 (I'm using v16.20.1). Please feel free to reopen if you still see the issue, thanks.

**Comment by KartikDevelopment** [comment]
> Sorry to miss your question for a while. It should work with node version v16 (I'm using v16.20.1). Please feel free to reopen if you still see the issue, thanks.

Dhanyawad
