### ISSUE TITLE
[Help] Use of some devDependencies

### ISSUE THREAD

**Issue by burhanuday** [WataruMaeda/react-native-boilerplate#6]
Can you please explain what the uses of each of these are in context of this boilerplate?

- mem
- minimist
- ws

**Comment by wataru-maeda** [comment]
Hi @burhanuday , thank you for your question. These are added when I resolve the potential security vulnerability warnings. But it seems we don't need the packages (The latest expo project doesn't include these). I will update the package, thanks.

**Comment by burhanuday** [comment]
Thank you
