### ISSUE TITLE
'watchman' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by eniskalyon** [WataruMaeda/react-native-boilerplate#66]
following npm install and installing packages,
npm run start command gives the following error:

"> react-native-boilerplate@1.0.0 prestart
> watchman watch-del-all

'watchman' is not recognized as an internal or external command,
operable program or batch file."

**Comment by wataru-maeda** [comment]
Hi @eniskalyon, That’s interesting! Have you installed Watchman? [React Native Environment Setup](https://reactnative.dev/docs/set-up-your-environment).

**Comment by eniskalyon** [comment]
I am using Expo in my usual workflow therefore I haven't installed watchman manually. I'll try installing that. Great work otherwise, thank you.

**Comment by wataru-maeda** [comment]
Thank you for the update. I’ll go ahead and close this issue for now. If you encounter any further problems, please don’t hesitate to comment here or open a new issue. Thank you!
